### ISSUE TITLE
Test actual backlash in legs

### ISSUE THREAD

**Issue by texhnolyze** [bit-bots/bitbots_hardware#42]
To clarify if we need software changes we want to test the actual backlash of our legs/motors:
- currently
- with serviced/new motors

**Comment by timonegk** [comment]
Also evaluate recalibrating rotated by 90°

**Comment by jaagut** [comment]
This has been done on Jack and Rory. Results are in our cloud storage at `BibBots-Home-Public/backlash.ods`
Motors have been swapped 90°, recalibrated and redistributed according to their performance.
